<a href="https://colab.research.google.com/github/Manitchahar/ML-Algo/blob/main/Word2vec_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 98.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 125.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 16.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.2
    Uninstalling scipy-1.16.2:
      Successfully uninstalled scipy-1.16.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requ

In [1]:
import gensim

In [2]:
from gensim.models import Word2Vec, KeyedVectors

In [3]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [5]:
import gensim.downloader as api

# Get the list of available models
available_models = list(api.info()['models'].keys())

# Print the number of available models
print(f"There are {len(available_models)} models available in gensim.downloader.")

# Optionally, print the list of available models
# print("Available models:")
# for model_name in available_models:
#     print(model_name)

There are 13 models available in gensim.downloader.
Available models:
fasttext-wiki-news-subwords-300
conceptnet-numberbatch-17-06-300
word2vec-ruscorpora-300
word2vec-google-news-300
glove-wiki-gigaword-50
glove-wiki-gigaword-100
glove-wiki-gigaword-200
glove-wiki-gigaword-300
glove-twitter-25
glove-twitter-50
glove-twitter-100
glove-twitter-200
__testing_word2vec-matrix-synopsis


In [6]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [8]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [13]:
wv.most_similar('macbook')

[('macbook_pro', 0.7480594515800476),
 ('Macbook', 0.7128286361694336),
 ('powerbook', 0.6734164357185364),
 ('MacBook', 0.6724260449409485),
 ('MacBookPro', 0.6655839085578918),
 ('droid_x', 0.6528066396713257),
 ('Macbook_Pro', 0.6518736481666565),
 ('hdd', 0.6510031223297119),
 ('##gb', 0.6489524245262146),
 ('compiz', 0.6460645794868469)]

In [16]:
wv.similarity('computer','laptop')

0.66404927

In [20]:
vec=wv['queen']-wv['man']+wv['woman']

In [21]:
vec

array([-0.07775879, -0.3515625 , -0.20703125,  0.09912109,  0.16015625,
       -0.1550293 ,  0.01269531, -0.19805908, -0.2290039 ,  0.10230255,
       -0.20166016, -0.47460938,  0.125     ,  0.02555084,  0.20776367,
        0.16625977, -0.01708984, -0.15966797,  0.09863281,  0.16430664,
        0.29223633,  0.08732605, -0.31762695, -0.2553711 ,  0.01159668,
       -0.09423828, -0.4013672 ,  0.09570312,  0.16308594, -0.3334961 ,
       -0.17480469, -0.2738037 , -0.24414062,  0.12805176, -0.375     ,
       -0.2626953 ,  0.15478516,  0.34179688, -0.26220703,  0.0625    ,
       -0.08178711, -0.40551758,  0.21582031, -0.04388428,  0.08300781,
       -0.06787109, -0.00411987,  0.17041016,  0.17736816,  0.38183594,
        0.16833496, -0.02475739,  0.05273438,  0.19091797, -0.32177734,
       -0.04492188, -0.35839844, -0.19970703,  0.23632812, -0.06408691,
        0.25878906,  0.1484375 , -0.05200195,  0.23925781,  0.1262207 ,
       -0.13476562,  0.11724854,  0.42382812, -0.10498047,  0.07

In [22]:
wv.most_similar([vec])

[('queen', 0.9020103812217712),
 ('princess', 0.678496241569519),
 ('queens', 0.6640722155570984),
 ('very_pampered_McElhatton', 0.607458233833313),
 ('Queen_Consort', 0.5709424614906311),
 ('Queen', 0.5660458207130432),
 ('princesses', 0.5634073615074158),
 ('monarch', 0.5554009079933167),
 ('duchess', 0.5510952472686768),
 ('empress', 0.5418459177017212)]